apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: mlops-housing
  labels:
    app: api-service
    component: api
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-metrics
  namespace: mlops-housing
  labels:
    app: api-service
    component: api-metrics
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    app: api-service