apiVersion: v1
kind: Service
metadata:
  name: predict-service
  namespace: mlops-housing
  labels:
    app: predict-service
    component: predict
    app.kubernetes.io/name: predict-service
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: predict
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: predict-service
---
apiVersion: v1
kind: Service
metadata:
  name: predict-service-metrics
  namespace: mlops-housing
  labels:
    app: predict-service
    component: predict-metrics
    app.kubernetes.io/name: predict-service
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: metrics
  selector:
    app: predict-service