# Pod Disruption Budget for API Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-service-pdb
  namespace: mlops-housing
  labels:
    app: api-service
    app.kubernetes.io/name: api-service-pdb
    app.kubernetes.io/part-of: mlops-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-service
      
---
# Pod Disruption Budget for Predict Service
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: predict-service-pdb
  namespace: mlops-housing
  labels:
    app: predict-service
    app.kubernetes.io/name: predict-service-pdb
    app.kubernetes.io/part-of: mlops-platform
spec:
  minAvailable: 1  # At least 1 pod should be available
  selector:
    matchLabels:
      app: predict-service