name: CI/CD Pipeline with Docker

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

jobs:
  test-api-service:
    name: Test API Service
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-api-${{ hashFiles('services/api/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-api-
          
    - name: Install dependencies
      working-directory: ./services/api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        # python -m pytest services/api/tests/ -v --cov=services/api/app --cov-report=xml --cov-report=term
        python scripts/run_tests.py --unit --quiet
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: api-service
        name: api-service-coverage

  test-predict-service:
    name: Test Predict Service
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-predict-${{ hashFiles('services/predict/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-predict-
          
    - name: Install dependencies
      working-directory: ./services/predict
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        # python -m pytest services/predict/tests/ -v --cov=services/predict/app --cov-report=xml --cov-report=term
        python scripts/run_tests.py --unit --quiet
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: predict-service
        name: predict-service-coverage

  build-api-service:
    name: Build API Service Docker Image
    runs-on: ubuntu-latest
    needs: test-api-service
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REPOSITORY }}/api-service
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/api
        file: ./services/api/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-predict-service:
    name: Build Predict Service Docker Image
    runs-on: ubuntu-latest
    needs: test-predict-service
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REPOSITORY }}/predict-service
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./services/predict
        file: ./services/predict/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-api-service, build-predict-service]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build services for testing
      run: |
        docker build -t api-service:test ./services/api
        docker build -t predict-service:test ./services/predict
        
    - name: Run integration tests
      run: |
        # Start services
        docker run -d --name predict-service --network host predict-service:test
        docker run -d --name api-service --network host api-service:test
        
        # Wait for services to be ready
        sleep 30
        
        # Run basic health checks
        curl -f http://localhost:8001/health || exit 1
        curl -f http://localhost:8000/health || exit 1
        
        # Clean up
        docker stop api-service predict-service
        docker rm api-service predict-service

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [build-api-service, build-predict-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner - Service 1
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_REPOSITORY }}/api-service:${{ github.sha }}
        format: 'sarif'
        output: 'api-service-trivy-results.sarif'
        
    - name: Run Trivy vulnerability scanner - Service 2
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_REPOSITORY }}/predict-service:${{ github.sha }}
        format: 'sarif'
        output: 'predict-service-trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: '.'

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [integration-test, security-scan]
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your deployment commands here
        # This could involve updating Kubernetes manifests, docker-compose files, etc.